version: "3.7"
services:
  app:
    build:
      args:
        user: lara-nuxt
        uid: 1000
      context: ../backend/.
      dockerfile: ../docker/backend/Dockerfile
    image: lara-nuxt-backend
    container_name: lara-nuxt-app
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ../backend/./:/var/www/backend
    networks:
      - lara-nuxt

  db:
    image: mysql:5.7
    container_name: lara-nuxt-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - lara-nuxt

  nginx:
    image: nginx:alpine
    container_name: lara-nuxt-nginx
    restart: unless-stopped
    ports:
      - ${BACK_END_PORT}:80
      - ${BACK_END_PORT_HTTPS}:443
    volumes:
      - ../backend/.:/var/www/backend
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lara-nuxt

networks:
  lara-nuxt:
    driver: bridge
